spring:
  application:
    name: InfyGoFlightMS   
 
  datasource:
    url: jdbc:mysql://localhost:3306/infygo_flight_ms
 
server:
  servlet.context-path: /InfyGoFlightMS
  port: 8002

logging:
  file: Errorlog.log
  level:
    root: info
    com.infoys.irs: info
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss,SSS} %5p [%t] %c [%M] - %m%n"