spring:
  application:
    name: InfyGoBookingMS   
 
  datasource:
    url: jdbc:mysql://localhost:3306/infygo_booking_ms

server:
  servlet.context-path: /InfyGoBookingMS
  port: 8004

logging:
  file: Errorlog.log
  level:
    root: info
    com.infoys.irs: info
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss,SSS} %5p [%t] %c [%M] - %m%n"