spring:
  application:
    name: InfyGoPaymentMS    
 
  datasource:
    url: jdbc:mysql://localhost:3306/infygo_payment_ms

server:
  servlet.context-path: /InfyGoPaymentMS
  port: 8003
 
logging:
  file: Errorlog.log
  level:
    root: info
    com.infoys.irs: info
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss,SSS} %5p [%t] %c [%M] - %m%n"